version: 2
updates:
  - package-ecosystem: nuget
    directories:
      - /src/NovaBrowser
      - /tests/NovaBrowser.Checks
      - /tests/NovaBrowser.UiChecks
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
