blank_issues_enabled: false
contact_links:
  - name: Sikkerhetsrapportering
    url: https://github.com/Darschnid479/NovaBrowser/blob/main/SECURITY.md
    about: Les dette før du deler sensitiv informasjon.
