name: Forslag til forbedring
description: Beskriv problemet før du foreslår løsningen.
title: "[Forslag]: "
body:
  - type: textarea
    id: problem
    attributes:
      label: Hvilket problem vil dette løse?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Hvordan bør det fungere?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternativer og mulige ulemper
  - type: textarea
    id: testing
    attributes:
      label: Hvordan kan vi se at dette faktisk blir bedre?
